### ISSUE TITLE
쿼리문제인데 이상한 CORS 네트워크 오류가 발생 희안..

### ISSUE THREAD

**Issue by min9nim** [min9nim/little-jesus-vue#12]
아래 쿼리인데.. 응답에서 items.type.priority 필드만 제거하면 오류 발생은 안하던데.. 포함하면 아래 이상한 오류가 발생해서 한참 당황했었음.. 
```graphql
 query pointsFromTo($startDate: String!, $endDate: String!) {
    res: pointsFromTo(startDate: $startDate, endDate: $endDate) {
      _id
      owner {
        _id
        name
        teacher {
          _id
          name
        }
      }
      date
      attendance
      meditation
      invitation
      visitcall
      recitation
      items {
        type {
          _id
          label
          type
          priority
          disable
        }
        value
      }
      etc
    }
  }
```

오류메세지 희안하네..
```js
{
  "message": "Network Error",
  "name": "Error",
  "stack": "Error: Network Error\n    at createError (webpack-internal:///./node_modules/axios/lib/core/createError.js:16:15)\n    at XMLHttpRequest.handleError (webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:81:14)\n    at XMLHttpRequest.sentryWrapped (webpack-internal:///./node_modules/@sentry/browser/esm/helpers.js:83:23)",
  "config": {
    "url": "https://little-jesus-api-git-develop.min1.now.sh",
    "method": "post",
    "data": "{\"query\":\"query pointsFromTo($startDate: String!, $endDate: String!) {\\n  res: pointsFromTo(startDate: $startDate, endDate: $endDate) {\\n    _id\\n    owner {\\n      _id\\n      name\\n      teacher {\\n        _id\\n        name\\n      }\\n    }\\n    date\\n    attendance\\n    meditation\\n    invitation\\n    visitcall\\n    recitation\\n    items {\\n      type {\\n        _id\\n        label\\n        type\\n        priority\\n        disable\\n      }\\n      value\\n    }\\n    etc\\n  }\\n}\\n\",\"variables\":{\"startDate\":\"20191001\",\"endDate\":\"20191231\"}}",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json"
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1
  }
}
```

**Comment by min9nim** [comment]
더 웃긴 건 저게 동일 소스인데 로컬 api 서버에서는 오류 발생이 안돼;;

**Comment by min9nim** [comment]
플레이그라운드에서 dev 백엔드 오류도 신기

![image](https://user-images.githubusercontent.com/6068828/71384318-f5563580-2623-11ea-8fef-482fc0316735.png)

**Comment by min9nim** [comment]
## 쿼리문제가 아니라 응답데이터의 크기 문제
기간을 짧게해서 쿼리하면 정상

## Solution
응답데이터의 길이를 최대한 짧게하라!

**Comment by min9nim** [comment]
`getPointSumOfWeek` 가  `item.type.priority` 에 직접 접근하지 않고 `pointMenus` 를 인자로 받아서 합계 점수를 계산할 수 있도록 수정하는 것이 관전포인트가 되겠다
```javascript
export function getPointSumOfWeek(point: any) {
  return point.items.reduce((acc: number, item: any) => acc + item.type.priority * item.value, 0)
}
```
