### ISSUE TITLE
테스트케이스가 element-ui 의존성을 가질 때 오류

### ISSUE THREAD

**Issue by min9nim** [min9nim/little-jesus-vue#17]
```

> mocha -r test/mocha.env -r ts-node/register -p tsconfig.mocha.json -r tsconfig-paths/register test/**/*.spec.ts test/**/**/*.spec.ts


/Users/mac9/project/side-p/little-jesus-vue/node_modules/element-ui/lib/utils/dom.js:22
var ieVersion = isServer ? 0 : Number(document.documentMode);
                                      ^
ReferenceError: document is not defined
    at Object.<anonymous> (/Users/mac9/project/side-p/little-jesus-vue/node_modules/element-ui/lib/utils/dom.js:22:39)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/mac9/project/side-p/little-jesus-vue/node_modules/element-ui/lib/utils/popup/popup-manager.js:9:12)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/mac9/project/side-p/little-jesus-vue/node_modules/element-ui/lib/utils/popup/index.js:14:21)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/mac9/project/side-p/little-jesus-vue/node_modules/element-ui/lib/utils/vue-popper.js:9:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/mac9/project/side-p/little-jesus-vue/node_modules/element-ui/lib/select.js:207:18)
    at __webpack_require__ (/Users/mac9/project/side-p/little-jesus-vue/node_modules/element-ui/lib/select.js:21:30)
    at Module.<anonymous> (/Users/mac9/project/side-p/little-jesus-vue/node_modules/element-ui/lib/select.js:1079:19)
    at __webpack_require__ (/Users/mac9/project/side-p/little-jesus-vue/node_modules/element-ui/lib/select.js:21:30)
    at /Users/mac9/project/side-p/little-jesus-vue/node_modules/element-ui/lib/select.js:85:18
    at Object.<anonymous> (/Users/mac9/project/side-p/little-jesus-vue/node_modules/element-ui/lib/select.js:88:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/mac9/project/side-p/little-jesus-vue/node_modules/element-ui/lib/element-ui.common.js:302:18)
    at __webpack_require__ (/Users/mac9/project/side-p/little-jesus-vue/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at Module.<anonymous> (/Users/mac9/project/side-p/little-jesus-vue/node_modules/element-ui/lib/element-ui.common.js:729:15)
    at __webpack_require__ (/Users/mac9/project/side-p/little-jesus-vue/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at Object.<anonymous> (/Users/mac9/project/side-p/little-jesus-vue/node_modules/element-ui/lib/element-ui.common.js:356:18)
    at __webpack_require__ (/Users/mac9/project/side-p/little-jesus-vue/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at /Users/mac9/project/side-p/little-jesus-vue/node_modules/element-ui/lib/element-ui.common.js:85:18
    at Object.<anonymous> (/Users/mac9/project/side-p/little-jesus-vue/node_modules/element-ui/lib/element-ui.common.js:88:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/mac9/project/side-p/little-jesus-vue/src/views/points.fn.ts:6:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Module.m._compile (/Users/mac9/project/side-p/little-jesus-vue/node_modules/ts-node/src/index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/mac9/project/side-p/little-jesus-vue/node_modules/ts-node/src/index.ts:539:12)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/mac9/project/side-p/little-jesus-vue/test/src/views/point.fn.spec.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Module.m._compile (/Users/mac9/project/side-p/little-jesus-vue/node_modules/ts-node/src/index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/mac9/project/side-p/little-jesus-vue/node_modules/ts-node/src/index.ts:539:12)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /Users/mac9/project/side-p/little-jesus-vue/node_modules/mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/mac9/project/side-p/little-jesus-vue/node_modules/mocha/lib/mocha.js:331:14)
    at Mocha.run (/Users/mac9/project/side-p/little-jesus-vue/node_modules/mocha/lib/mocha.js:809:10)
    at Object.exports.singleRun (/Users/mac9/project/side-p/little-jesus-vue/node_modules/mocha/lib/cli/run-helpers.js:108:16)
    at exports.runMocha (/Users/mac9/project/side-p/little-jesus-vue/node_modules/mocha/lib/cli/run-helpers.js:142:13)
    at Object.exports.handler (/Users/mac9/project/side-p/little-jesus-vue/node_modules/mocha/lib/cli/run.js:292:3)
    at Object.runCommand (/Users/mac9/project/side-p/little-jesus-vue/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/Users/mac9/project/side-p/little-jesus-vue/node_modules/yargs/yargs.js:1087:28)
    at Object.parse (/Users/mac9/project/side-p/little-jesus-vue/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/Users/mac9/project/side-p/little-jesus-vue/node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> (/Users/mac9/project/side-p/little-jesus-vue/node_modules/mocha/bin/mocha:164:29)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! little-jesus-vue@0.1.1 test: `mocha -r test/mocha.env -r ts-node/register -p tsconfig.mocha.json -r tsconfig-paths/register test/**/*.spec.ts test/**/**/*.spec.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the little-jesus-vue@0.1.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac9/.npm/_logs/2020-01-07T00_52_23_470Z-debug.log
The terminal process terminated with exit code: 1
```

**Comment by min9nim** [comment]
vue 가 SSR 모드로 로드되지 않아서 발생한 문제

![image](https://user-images.githubusercontent.com/6068828/71859810-a59f6000-3133-11ea-835d-780a03201ecf.png)

vue 의 $isServer 를 true 로 설정하려면 `process.env.VUE_ENV = 'server'` 가 필요



ref) https://github.com/vuejs/vue/blob/dev/src/core/util/env.js#L41
